---
title: "eTRF offspring body composition analysis"
author: "Molly C. Mulcahy"
date: "2/25/2021"
output: html_document
---
#This document contains primary data and analysis for the dissertation work involving early time-restricted feeding during gestation effect on mouse offspring

#setup chunk
```{r setup, include=FALSE}
library(processx)
library(devtools)
library(dplyr)
library(readr)
library(car)
library(knitr)
library(tidyr)
library(lme4)
library(broom)
library(RCurl)
library(ggplot2)

#figures made will go to directory called figures, will make them as both png and pdf files 
opts_chunk$set(fig.path='figures/',
               echo=FALSE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
options(scipen = 2, digits = 3)
# set echo and message to TRUE if you want to display code blocks and code output respectively
knitr::knit_hooks$set(inline = function(x) {
  knitr:::format_sci(x, 'md')
})
#write standard error function for later use
se <- function(x) sd(x, na.rm=T)/sqrt(length(x))
# sets color scheme for plots
color.scheme <- c('gray69','gray36')
```

#Data Entry
```{r data-entry-MRI}
MRI.data.file<-"MRI.Off.data.csv"
MRI.raw.data<-read_csv(MRI.data.file,
                       col_types = cols(
  ID = col_factor(levels = NULL),
  age = col_double(),
  animal.id = col_factor(levels = NULL),
  MouseID = col_factor(levels = NULL),
  Sex = col_factor(levels = NULL),
  Genotype = col_factor(levels = NULL),
  values = col_double(),
  assay = col_factor(levels = NULL),
  experiment.date = col_date(format = ""),
  treatment = col_factor(levels = NULL),
  dam = col_factor(levels = NULL),
  cohort = col_factor(levels = NULL),
  gram.values = col_double()))
```
#Pre-HFD analysis (PND 21- PND 70)
#Body Composition
```{r Figure-2-A-B-C}
#table of unique animals for body composition numbers
MRI.raw.data %>%
  group_by(Sex,treatment) %>%
  distinct(ID, .keep_all = T) %>%
  count %>%
  kable(caption="Animals in each group of this cohort")
#Body Weight data table
BW.data<-filter(MRI.raw.data, assay=="Body Weight")%>%
  filter(age<70)%>%
  group_by(age, treatment, Sex)%>%
  summarize_if(is.numeric, .funs = funs(mean=mean(.,na.rm = TRUE),se=se, n=length))
##Body Weight plot
ggplot(BW.data,aes(age, gram.values_mean, col = treatment))+
  geom_point(aes(col = treatment))+
  geom_smooth(span = 0.7,aes(col = treatment), se = FALSE)+
  facet_grid(.~Sex)+
  scale_color_manual(values = color.scheme)+
  labs(title = "Offspring Body Weight", y = "Body weight (grams)",x="Age (days)")+
  theme(text = element_text(size=16),legend.position = c(0.9,0.19))
#Lean Mass data table
LM.data<-filter(MRI.raw.data, assay=="Lean Mass")%>%
  filter(age<70)%>%
  group_by(age, treatment, Sex)%>%
  summarize_if(is.numeric, .funs = funs(mean=mean(.,na.rm = TRUE),se=se, n=length))
#Lean Mass Plot
ggplot(LM.data,aes(age, gram.values_mean, col = treatment))+
  geom_point(aes(col = treatment))+
  geom_smooth(span = 0.7,aes(col = treatment), se = FALSE)+
  facet_grid(.~Sex)+
  scale_color_manual(values = color.scheme)+
  labs(title = "Offspring Lean Mass", y = "Lean Mass (grams)",x="Age (days)")+
  theme(text = element_text(size=16),legend.position = c(0.9,0.80))
#Body Fat Data table
FM.data<-filter(MRI.raw.data, assay=="Total Fat Mass")%>%
  filter(age<70)%>%
  group_by(age, treatment, Sex)%>%
  summarize_if(is.numeric, .funs = funs(mean=mean(.,na.rm = TRUE),se=se, n=length))
#Body Fat Plot
ggplot(FM.data,aes(age, gram.values_mean, col = treatment))+
  geom_point(aes(col = treatment))+
  geom_smooth(span = 0.7,aes(col = treatment), se = FALSE)+
  facet_grid(.~Sex)+
  scale_color_manual(values = color.scheme)+
  labs(title = "Offspring Fat Mass", y = "Fat Mass (grams)",x="Age (days)")+
  theme(text = element_text(size=16),legend.position = c(0.9,0.80))

#Body Composition stats

#Body Weight 
BW.data.stats <-MRI.raw.data%>%
  filter(assay ==    "Body Weight")
null.lme<-lmer(gram.values ~ 1 + (1|MouseID) + (1|dam), data = BW.data.stats)
age.lme <-lmer(gram.values ~ age + (1|MouseID) + (1|dam), data = BW.data.stats)
anova(null.lme, age.lme)#significant
diet.lme<-lmer(gram.values ~ age*treatment + (1|MouseID) + (1|dam), data = BW.data.stats)
anova(age.lme, diet.lme)#significant diet age interaction
#Females

#males
```
#Food Intake Data
```{r data-entry-intake}
intake.data.raw<-("Intake.Off.data.csv")
intake.data<-read_csv(intake.data.raw,
                      col_types = cols(
                        cage = col_factor(levels = NULL),
                        "# in cage" = col_double(),
                        week = col_integer(),
                        "IDs" = col_factor(levels = NULL),
                        start = col_double(),
                        end=col_double(),
                        date = col_character(),
                        notes = col_factor(levels=NULL),
                        diet = col_factor(levels = NULL),
                        cohort = col_factor(levels = NULL),
                        food.consumed = col_double(),
                        kcals.consumed = col_double(),
                        food.cumulative = col_double(),
                        treatment = col_factor(levels = c("eTRF","AL")),
                        sex = col_factor(levels = NULL)
                        ))
```

#Food Intake
```{r pre-HFD-intake}
#Table of Cages in Food Intake Analyses
intake.data %>%
  group_by(sex,treatment) %>%
  distinct(cage, .keep_all = T) %>%
  count %>%
  kable(caption="Cages in each group")

#make averaged dataset
average.intake<-intake.data%>%
   filter(!(week=="5"&cage=="2031"))%>%
  group_by(week, diet, treatment, sex)%>%
  summarize_if(is.numeric, .funs = funs(mean=mean(.,na.rm = TRUE),se=se, n=length))

#Filter out HFD from dataset
Pre.HFD.data<-average.intake%>%
  filter(diet=="NCD")

#Plot of averaged.intake
ggplot(Pre.HFD.data, aes(week, kcals.consumed_mean,col = treatment))+
  geom_point(aes(col = treatment))+
  geom_smooth(aes(col = treatment), se=FALSE, span =0.7)+
  geom_errorbar(aes(ymin = kcals.consumed_mean -kcals.consumed_se, ymax = kcals.consumed_mean +kcals.consumed_se), width = 0.3)+
  facet_grid(.~sex)+
  labs(title="Food Intake", subtitle = "average kcals per cage per week", y = "Food Intake (kcals)", x="Week")+
  scale_color_manual(values = color.scheme)+
   theme(text = element_text(size=16),legend.position = c(0.1,0.80))

#cumulative intake plot
ggplot(Pre.HFD.data, aes(week, food.cumulative_mean, col = treatment))+
  geom_point(aes(col = treatment))+
  geom_smooth(aes(col = treatment), se=FALSE)+
  geom_errorbar(aes(ymin = food.cumulative_mean -food.cumulative_se, ymax = food.cumulative_mean +food.cumulative_se), width = 0.3)+
  facet_grid(.~sex)+
  labs(x="Week",y="Cumulative Food Intake (kcals)")+
  ggtitle("Cumulative Food Intake, NCD")+
  scale_color_manual(values = color.scheme)+
  theme(text = element_text(size=16),legend.position = c(0.1,0.80))

#statistics for weekly food intake

#statistics for culumaltive food intake

```
