---
title: "dam ITT"
author: "Molly C. Mulcahy"
date: '2022-05-31'
output: html_document
---

```{r setup}
#load commonly needed packages
library(processx)
library(devtools)
library(tidyr)
library(dplyr)
library(readr)
library(ggplot2)
library(knitr)
library(car)
library(lme4)
library(broom)
library(forcats)

#figures made will go to directory called figures, will make them as both png and pdf files 
opts_chunk$set(fig.path='figures/',
               echo=FALSE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
options(scipen = 2, digits = 3)
# set echo and message to TRUE if you want to display code blocks and code output respectively
knitr::knit_hooks$set(inline = function(x) {
  knitr:::format_sci(x, 'md')
})
se <- function(x) sd(x, na.rm=T)/sqrt(length(x))

#set plot color scheme
color.scheme = c("#333333","#CCCCCC")
defense.color.scheme<- c("#00274C","#A5A508")
```


```{r data-entry}
ITT.file<-"dam.ITT.csv"

ITT.data<-read_csv(ITT.file,
    col_types = cols(
    MouseID = col_factor(levels = NULL),
    time = col_double(),
    glucose = col_double(),
    Genotype = col_factor(levels = c("+/+","-/-")),
    AUC = col_double(),
    rel.glucose = col_double(),
    rel.auc = col_double()))   %>%
  mutate(Genotype=fct_recode(Genotype,
                             "Wild-type"="+/+",
                             "GDF15 Knockout"="-/-"))

avg.data<- ITT.data%>%
  group_by(time, Genotype)%>%
  summarize_at("glucose", funs(mean, se))
```

```{r time-course}
 ITT.data%>%
  group_by(time, Genotype)%>%
  summarize_at("glucose", funs(mean, se))%>%
  ggplot(aes(time, mean, col = Genotype))+
  geom_point(aes(col = Genotype))+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se, col = Genotype), width =0.3)+
  scale_color_manual(values = color.scheme)+
  geom_line(aes(col = Genotype))+
  labs(title = "Insulin tolerance test", y= "mg/dL")+
  theme(legend.position = c(0.85, 0.85))+
  theme_bw(base_size=18)

#stat
null.glu<-lmer(glucose ~ 1+(1|MouseID), data = ITT.data)
time.glu<-lmer(glucose ~ time + (1|MouseID), data = ITT.data)
anova(null.glu, time.glu)#significant effect of time
geno.glu<-lmer(glucose ~ time + Genotype +(1|MouseID), data = ITT.data)
anova(time.glu, geno.glu)#no effect of genotype
geno.int.glu<-lmer(glucose ~  time*Genotype+(1|MouseID), data = ITT.data)
Anova(geno.int.glu)#no genotype effect, p=0.071
anova(geno.glu, geno.int.glu)#0.07
Anova(geno.glu)
fixef(geno.glu)

```


```{r rel-timecourse}
ITT.data%>%
  group_by(time, Genotype)%>%
  summarize_at("rel.glucose", funs(mean, se))%>%
ggplot(aes(time, mean, col = Genotype))+
  geom_point(aes(col = Genotype))+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se, col = Genotype), width =0.3)+
  scale_color_manual(values = color.scheme)+
  geom_line(aes(col = Genotype))+
  labs(title = "Insulin Tolerance Test", y= "Relative Glucose (% of Baseline)",x="Insulin (minutes)")+
  theme_bw(base_size=18)+
  theme(legend.position = c(0.75, 0.85),legend.background = element_blank())
  

#stats
null.rel <- lmer(glucose ~ 1 + (1|MouseID), ITT.data)
time.rel <- lmer(glucose ~ time + (1|MouseID), ITT.data)
anova(null.rel, time.rel)#significant effect of time
geno.rel<- lmer(glucose ~ time + Genotype + (1|MouseID), ITT.data)
anova(time.rel, geno.rel)#p=0.68
geno.int.rel<-lmer(glucose ~ time*Genotype + (1|MouseID), ITT.data)
anova(geno.rel, geno.int.rel)#p=0.07
Anova(geno.int.rel)
Anova(geno.rel)
```


```{r Fasting-BG}
ITT.data%>%
  filter(time == "0")%>%
  group_by(Genotype)%>%
  summarize_at("glucose", funs(mean, se))%>%
  ggplot(aes(Genotype, mean, fill = Genotype))+
  geom_col(aes(fill = Genotype))+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width =0.3)+
  scale_fill_manual(values = color.scheme)+
  labs(title = "Fasting Blood Glucose", y = "glucose (mg/dL)")+
   theme_bw(base_size=18)+
  theme(legend.position = "none")
#stats
FBG.data <-ITT.data%>%
  filter(time == "0")
shapiro.test(FBG.data$glucose[FBG.data$Genotype=="GDF15 Knockout"])#normal
shapiro.test(FBG.data$glucose[FBG.data$Genotype=="Wild-type"])#normal
leveneTest(glucose ~ Genotype, data = FBG.data)#equal variance
t.test(glucose ~ Genotype, data = FBG.data)#p=0.20
```


```{r AUC}
AUC.data<-ITT.data%>%
  select(MouseID, Genotype, AUC)%>%
  group_by(MouseID)%>%
  unique

AUC.data%>%
  group_by(Genotype)%>%
  summarize_at("AUC", funs(mean, se))%>%
  ggplot(aes(Genotype, mean, fill = Genotype))+
  geom_col(aes(fill = Genotype))+
  geom_errorbar(aes(ymax = mean + se, ymin = mean - se), width =0.3)+
  scale_fill_manual(values = color.scheme)+
  labs(title = "Area Under the Curve", y = "Glucose (mg/dL)")+
  theme_bw()+
  theme(legend.position = "none",text = element_text(size=14))
#stats
shapiro.test(AUC.data$"AUC"[AUC.data$Genotype=="Wild-type"])#normal
shapiro.test(AUC.data$"AUC"[AUC.data$Genotype=="GDF15 Knockout"])#normal
leveneTest(AUC ~ Genotype, data = AUC.data)#not equal variance
t.test(AUC ~ Genotype, data = AUC.data,var.equal = FALSE)$p.value%>%tidy%>%kable#0.7
```


```{r rate-of-drop}
#calculate rate of drop
models<-ITT.data%>%
  filter(time<60)%>%
  group_by(MouseID,Genotype)%>%
  mutate(l.glucose = log(glucose))%>%
  do(fitted.model= lm(l.glucose~ time, data =.))%>%
  mutate(rate =coef(fitted.model)["time"],
          max = coef(fitted.model)["(Intercept)"],
         rsq = summary(fitted.model)$r.squared)%>%
  mutate(max.exp = exp(max))%>%
  mutate( slope= max.exp*rate)
summary.models<-models%>%
  group_by(Genotype)%>%
summarise_at("slope",  funs(mean, se))


#plot
ggplot(summary.models, aes(Genotype, mean, fill = Genotype))+
  geom_col(aes(fill = Genotype))+
  geom_errorbar(aes(ymin = mean-se, ymax = mean + se), width = 0.3)+
  scale_fill_manual(values = color.scheme)+
  labs(title = "Initial Rate of Glucose Change",y="Rate of Glucose Decrease")+
  theme_bw()+
  theme(legend.position = "none",text = element_text(size=14)) 
#stats
shapiro.test(models$slope[models$Genotype=="GDF15 Knockout"])#normal
shapiro.test(models$slope[models$Genotype=="Wild-type"])#normal
leveneTest(slope~Genotype, data = models)#not equal variance
t.test(slope~Genotype, data = models,var.equal = FALSE)
```
           