---
title: "eTRF-maternal-ITT.rmd"
author: "Molly C. Mulcahy"
date: "2022-12-22"
output: html_document
---

```{r global_options, include=FALSE}
library(knitr)
library(readr)
library(tidyr)
library(ggplot2)
library(car)
library(lme4)
library(dplyr)
#figures makde will go to directory called figures, will make them as both png and pdf files 
opts_chunk$set(fig.path='figures/',
               echo=FALSE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
options(scipen = 2, digits = 3)
# set echo and message to TRUE if you want to display code blocks and code output respectively

knitr::knit_hooks$set(inline = function(x) {
  knitr:::format_sci(x, 'md')
})


superpose.eb <- function (x, y, ebl, ebu = ebl, length = 0.08, ...)
  arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3,
  length = length, ...)

  
se <- function(x) sd(x, na.rm=T)/sqrt(length(x))
# sets maize and blue color scheme
color.scheme <-  c('#999999','#333333')
```

```{r data-entry}
raw.data.file<-"dam.ITT.csv"

ITT.data<-read_csv(raw.data.file,
                   col_types = cols(
                     ID = col_factor(levels = NULL),
                     treatment = col_factor(levels = c("AL","eTRF")),
                     pregnancy = col_factor(levels = c("1","2")),
                     cohort = col_factor(levels = c("1","2","3")),
                     time = col_integer(),
                     glucose = col_double(),
                     dose.weight = col_double()
                   ))

```


```{r cohort-checks}
summary(lm(glucose ~ dose.weight + cohort, data = ITT.data))

ggplot(ITT.data, aes(dose.weight, glucose,col=treatment))+
  geom_point()
```

```{r FBG}
#plot
ITT.data%>%
  filter(time=="0")%>%
  group_by(treatment)%>%
  summarize(avg.FBG = mean(glucose),
            error.FBG = se(glucose))%>%
  ggplot(aes(treatment, avg.FBG, fill = treatment))+
  geom_col(aes(treatment))+
  geom_errorbar(aes(ymin = avg.FBG - error.FBG, ymax = avg.FBG + error.FBG),width =0.3)+
  scale_fill_manual(values = color.scheme)+
  labs(title = "Dam Fasting Blood Glucose", y = "Glucose (mg/dL)")+
   scale_fill_manual(values = color.scheme)+
  theme_bw()+
  theme(legend.position = "none",text = element_text(size=18), axis.title.x = element_blank())


FBG.data<-ITT.data%>%
  filter(time=="0")
shapiro.test(FBG.data$glucose[FBG.data$treatment =="eTRF"])#normal
shapiro.test(FBG.data$glucose[FBG.data$treatment =="AL"])#normal
leveneTest(glucose~treatment, data = FBG.data)#equal variance
t.test(glucose~treatment, data = FBG.data)$p.value
```
```{r AUC}
#generate AUC
AUC.data<-ITT.data%>%
  group_by(ID)%>%
  mutate(AUC = sum(glucose))%>%
  select(ID, treatment, cohort,AUC)%>%
  unique()
#Plot
AUC.data%>%
  group_by(treatment)%>%
  summarize(avg.auc = mean(AUC),
            error.auc = se(AUC))%>%
ggplot(aes(treatment, avg.auc, fill = treatment))+
         geom_col()+
  geom_errorbar(aes(ymin = avg.auc - error.auc, ymax = avg.auc + error.auc), width =0.3)+
  labs(title = "Area Under the Curve", y = "Glucose (mg/dL)")+
  scale_fill_manual(values = color.scheme)+
  theme_bw()+
  theme(legend.position = "none",text = element_text(size=18), axis.title.x = element_blank())
 

shapiro.test(AUC.data$AUC[AUC.data$treatment=="eTRF"])#normal
shapiro.test(AUC.data$AUC[AUC.data$treatment=="AL"])# not normal
leveneTest(AUC ~ treatment, data = AUC.data)# equivalent variance
wilcox.test(AUC ~ treatment, data = AUC.data, paired = FALSE)
```

```{r drop}
#rate of drop
models<-ITT.data%>%
  filter(time<45)%>%
  group_by(ID, treatment)%>%
  mutate(l.glucose = log(glucose))%>%
  do(fitted.model= lm(l.glucose~ time, data =.))%>%
  mutate(rate =coef(fitted.model)["time"],
          max = coef(fitted.model)["(Intercept)"],
         rsq = summary(fitted.model)$r.squared)%>%
  mutate(max.exp = exp(max))%>%
  mutate( slope= max.exp*rate)
summary.models<-models%>%
  group_by(treatment)%>%
summarise_at(.var ="slope", .funs = funs(mean, se))

#plot
ggplot(summary.models, aes(treatment, mean, fill = treatment))+
  geom_col(aes(fill = treatment))+
  geom_errorbar(aes(ymin = mean-se, ymax = mean + se), width = 0.3)+
  scale_fill_manual(values = color.scheme)+
  labs(title = "Rate of Glucose Decline",y="mg/dL per minute")+
   scale_fill_manual(values = color.scheme)+
  theme_bw()+
  theme(legend.position = "none",text = element_text(size=18), axis.title.x = element_blank())

shapiro.test(models$slope[models$treatment=="eTRF"])#normal
shapiro.test(models$slope[models$treatment=="AL"])#normal
leveneTest(slope ~ treatment, data = models)#equal variance
t.test(slope ~ treatment, data = models)$p.value
```

```{r rebound}
#rebound analysis
rebound<-ITT.data%>%
  filter(as.numeric(time) > 60)%>%
  group_by(ID, treatment)%>%
  do(fitted.model= lm(glucose~ time, data =.))%>%
  mutate(rate =coef(fitted.model)["time"],
         rsq = summary(fitted.model)$r.squared)
summary.rebound<-rebound%>%
  group_by(treatment)%>%
summarise_at(.var ="rate", .funs = funs(mean, se))

#plot
ggplot(summary.rebound, aes(treatment, mean, fill = treatment))+
  geom_col(aes(fill = treatment))+
  geom_errorbar(aes(ymin = mean-se, ymax = mean + se), width = 0.3)+
  scale_fill_manual(values = color.scheme)+
  labs(title = "Rate of Glucose Recovery",y="Delta Glucose (mg/dL/min)")+
   scale_fill_manual(values = color.scheme)+
  theme_bw()+
  theme(legend.position = "none",text = element_text(size=18), axis.title.x = element_blank())
  
shapiro.test(rebound$rate[rebound$treatment=="eTRF"])#normal
shapiro.test(rebound$rate[rebound$treatment=="AL"])#not normal
leveneTest(rate ~ treatment, data = rebound)
t.test(rate ~ treatment, data = rebound)$p.value
```

```{r time-course}
#modeling over time
#plot
ITT.data%>%
  group_by(time, treatment)%>%
  summarize(avg.glu = mean(glucose),
            error.glu = se(glucose))%>%
ggplot(aes(time, avg.glu, col = treatment))+
  geom_point()+
  geom_line(aes(col = treatment))+
  geom_errorbar(aes(ymin = avg.glu - error.glu, ymax = avg.glu + error.glu), width =0.4)+
  scale_color_manual(values = color.scheme)+
  theme_bw()+
  labs(title = "Insulin Tolerance Test, E16", y = "Glucose (mg/dL)" )+
  scale_x_continuous(breaks=seq(0, 120, 15))+
  theme(legend.position = c(0.23, 0.8),text = element_text(size=18), legend.background = element_blank())

#linear mixed effect modeling
null.ITT<-lmer(glucose~ 1 + (1|ID), data = ITT.data)
time.ITT<-lmer(glucose~ as.factor(time) + (1|ID), data = ITT.data)
anova(null.ITT, time.ITT)#p<0.001
simple.group.ITT<-lmer(glucose~ as.factor(time) + treatment + (1|ID), data = ITT.data)
anova(time.ITT, simple.group.ITT)#0.04
int.group.ITT<-lmer(glucose~ as.factor(time)*treatment + (1|ID), data = ITT.data)
anova(simple.group.ITT, int.group.ITT)#p<0.001
Anova(int.group.ITT)%>%kable(caption = "glucose~ time*treatment + (1|ID)")

fixef(int.group.ITT)
summary(int.group.ITT)#update methods too
```
